spring:
  application:
    name: Star-admin

  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/admin?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: xuguangming
    password: 13952803647x
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Redis 配置（完善版）
  data:
    redis:
        host: localhost
        port: 6379
        password:
        database: 0                        # 使用哪个数据库（0-15）
        timeout: 5s                        # 连接超时时间
        lettuce:                           # 使用 Lettuce 客户端（Spring Boot 2+ 默认）
          pool:
            max-active: 8                  # 最大连接数
            max-idle: 8                    # 最大空闲连接数
            min-idle: 0                    # 最小空闲连接数
            max-wait: -1ms                 # 获取连接的最大等待时间（-1 表示无限等待）



server:
  port: 10001

logging:
  file:
    name: C:\\Users\\HP\\Desktop\\Best\\Star\\backend\\Star-java\\Star-admin\\logs\\app.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"